title: Osvaldo Ruiz
email: oruiz.code@gmail.com
description: >-
                Data Analyst with 9+ years of leadership experience.

baseurl: ""
url: "https://ruizosvaldo.github.io"

github_username: ruizosvaldo
linkedin_username: osvaldoruiz
twitter_username: ORuizCode

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Resume
    url: /resume/
